# Generated by Django 6.0.5 on 2026-05-13 16:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('genre', models.CharField(choices=[('Action', 'Экшн'), ('Comedy', 'Комедия'), ('Drama', 'Драма'), ('Horror', 'Ужасы'), ('Sci-Fi', 'Научная фантастика')], max_length=50, verbose_name='Жанр')),
                ('year', models.PositiveIntegerField(verbose_name='Год выпуска')),
                ('status', models.CharField(choices=[('to_watch', 'Хочу посмотреть'), ('watching', 'Смотрю'), ('watched', 'Посмотрел')], default='to_watch', max_length=20, verbose_name='Статус')),
                ('rating', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Оценка (1-10)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
